### ISSUE TITLE
ROLLUP_DOC: how is this defined?

### ISSUE THREAD

**Issue by dparks1134** [LANL-Bioinformatics/GOTTCHA#11]
Hello,

I couldn't find an explanation for ROLLUP_DOC and am curious how this is calculated. It appears to be the recommended method for using GOTTCHA at this point so am interested in how it differs from LINEAR_DOC.

Thanks,
Donovan

**Comment by poeli** [comment]
Hello Donovan,

ROLLUP_DOC is the summation of average depth of coverage of unique signature length of each strain belonging to this taxonomy ( Σ<sub>i=strains</sub> ( TOTAL_BP_MAPPED<sub>i</sub> / unique_signature_length<sub>i</sub>) ).

We found ROLLUP_DOC can respresent abundance better since LINEAR_DOC over calculates abundnace in some cases like stacking reads at a short regions.

Please let me know if you have any other questions.

Thanks,
Paul
